INSERT INTO College (name, url) VALUES ('University of California, Berkeley', 'http://universityofcalifornia,berkeley.edu');
INSERT INTO College (name, url) VALUES ('Stanford University', 'http://stanforduniversity.edu');
INSERT INTO College (name, url) VALUES ('Massachusetts Institute of Technology', 'http://massachusettsinstituteoftechnology.edu');
INSERT INTO College (name, url) VALUES ('Harvard University', 'http://harvarduniversity.edu');
INSERT INTO College (name, url) VALUES ('California Institute of Technology', 'http://californiainstituteoftechnology.edu');
INSERT INTO College (name, url) VALUES ('Princeton University', 'http://princetonuniversity.edu');
INSERT INTO College (name, url) VALUES ('University of Chicago', 'http://universityofchicago.edu');
INSERT INTO College (name, url) VALUES ('Yale University', 'http://yaleuniversity.edu');
INSERT INTO College (name, url) VALUES ('Columbia University', 'http://columbiauniversity.edu');
INSERT INTO College (name, url) VALUES ('University of Pennsylvania', 'http://universityofpennsylvania.edu');
INSERT INTO College (name, url) VALUES ('Cornell University', 'http://cornelluniversity.edu');
INSERT INTO College (name, url) VALUES ('Dartmouth College', 'http://dartmouthcollege.edu');
INSERT INTO College (name, url) VALUES ('Brown University', 'http://brownuniversity.edu');
INSERT INTO College (name, url) VALUES ('University of Michigan', 'http://universityofmichigan.edu');
INSERT INTO College (name, url) VALUES ('University of California, Los Angeles', 'http://universityofcalifornia,losangeles.edu');
INSERT INTO College (name, url) VALUES ('University of California, San Diego', 'http://universityofcalifornia,sandiego.edu');
INSERT INTO College (name, url) VALUES ('University of Illinois at Urbana-Champaign', 'http://universityofillinoisaturbana-champaign.edu');
INSERT INTO College (name, url) VALUES ('University of Wisconsin-Madison', 'http://universityofwisconsin-madison.edu');
INSERT INTO College (name, url) VALUES ('University of Texas at Austin', 'http://universityoftexasataustin.edu');
INSERT INTO College (name, url) VALUES ('Duke University', 'http://dukeuniversity.edu');
INSERT INTO College (name, url) VALUES ('Johns Hopkins University', 'http://johnshopkinsuniversity.edu');
INSERT INTO College (name, url) VALUES ('Northwestern University', 'http://northwesternuniversity.edu');
INSERT INTO College (name, url) VALUES ('Washington University in St. Louis', 'http://washingtonuniversityinst.louis.edu');
INSERT INTO College (name, url) VALUES ('University of California, San Francisco', 'http://universityofcalifornia,sanfrancisco.edu');
INSERT INTO College (name, url) VALUES ('University of Florida', 'http://universityofflorida.edu');
INSERT INTO College (name, url) VALUES ('New York University', 'http://newyorkuniversity.edu');
INSERT INTO College (name, url) VALUES ('University of Southern California', 'http://universityofsoutherncalifornia.edu');
INSERT INTO College (name, url) VALUES ('Carnegie Mellon University', 'http://carnegiemellonuniversity.edu');
INSERT INTO College (name, url) VALUES ('University of Washington', 'https://universityofwashington.edu');
INSERT INTO College (name, url) VALUES ('Georgia Institute of Technology', 'http://georgiainstituteoftechnology.edu');
INSERT INTO College (name, url) VALUES ('University of North Carolina at Chapel Hill', 'http://universityofnorthcarolinaatchapelhill.edu');
INSERT INTO College (name, url) VALUES ('Boston University', 'http://bostonuniversity.edu');
INSERT INTO College (name, url) VALUES ('University of California, Davis', 'http://universityofcalifornia,davis.edu');
INSERT INTO College (name, url) VALUES ('University of Maryland, College Park', 'http://universityofmaryland,collegepark.edu');
INSERT INTO College (name, url) VALUES ('University of California, Santa Barbara', 'http://universityofcalifornia,santabarbara.edu');
INSERT INTO College (name, url) VALUES ('Vanderbilt University', 'http://vanderbiltuniversity.edu');
INSERT INTO College (name, url) VALUES ('University of California, Irvine', 'http://universityofcalifornia,irvine.edu');
INSERT INTO College (name, url) VALUES ('University of Virginia', 'http://universityofvirginia.edu');
INSERT INTO College (name, url) VALUES ('Tufts University', 'http://tuftsuniversity.edu');
INSERT INTO College (name, url) VALUES ('Emory University', 'http://emoryuniversity.edu');
INSERT INTO College (name, url) VALUES ('Rice University', 'http://riceuniversity.edu');
INSERT INTO College (name, url) VALUES ('University of Notre Dame', 'http://universityofnotredame.edu');
INSERT INTO College (name, url) VALUES ('University of Minnesota', 'http://universityofminnesota.edu');
INSERT INTO College (name, url) VALUES ('Ohio State University', 'http://ohiostateuniversity.edu');
INSERT INTO College (name, url) VALUES ('University of Colorado Boulder', 'http://universityofcoloradoboulder.edu');
INSERT INTO College (name, url) VALUES ('Pennsylvania State University', 'http://pennsylvaniastateuniversity.edu');
INSERT INTO College (name, url) VALUES ('University of Pittsburgh', 'http://universityofpittsburgh.edu');
INSERT INTO College (name, url) VALUES ('Purdue University', 'http://purdueuniversity.edu');
INSERT INTO College (name, url) VALUES ('Texas A&M University', 'http://texasa&muniversity.edu');
INSERT INTO College (name, url) VALUES ('Michigan State University', 'http://michiganstateuniversity.edu');
